---
- hosts: localhost

  vars:
   meraki_key: "{{ meraki_key }}"
   org_id: "{{ org_id }}"

  tasks:
    - name: Get Organization Networks
      cisco.meraki.networks_info:
        meraki_api_key: "{{ meraki_key }}"
        organizationId: "{{ org_id }}"
      register: result
      
    - name: Filter networks with "wireless" productTypes
      set_fact:
        filtered_networks: "{{ result.meraki_response | selectattr('productTypes', 'contains', 'wireless') | list }}"
      register: network_id_get

    ############## Add tasks below
