---
- name: Removing Network
  hosts: localhost
  vars:
    meraki_api_key: "{{ meraki_key }}"
    org_id: "{{ org_id }}"
    network_name: "{{ network_name }}"
    
  tasks:
  
    - name: Remove Network
      cisco.meraki.networks:
        meraki_api_key: "{{ meraki_key }}"
        organizationId: "{{ org_id }}"
        name: "{{ network_name }}"
        state: absent
